### ISSUE TITLE
Custom range for floats

### ISSUE THREAD

**Issue by IceSentry** [smol-rs/fastrand#18]
Currently, floats only generate in a range of 0..1

It's pretty easy to convert it in the user side to a specific range, but is there a reason why there isn't a way to do this directly? Since this would be a breaking change, maybe add a fastrand::f64_range(range).

**Comment by taiki-e** [comment]
The current one has the same behavior as [rand's `random`](https://docs.rs/rand/0.8.4/rand/fn.random.html#provided-implementations). 

However, I don't think there is any reason why `{f32,f64}_range` is not available, so I would accept a PR to add `{f32,f64}_range`.

**Comment by notgull** [comment]
This is now exposed in [`fastrand-contrib`](https://crates.io/crates/fastrand-contrib) v0.1.0.
