### ISSUE TITLE
gen same

### ISSUE THREAD

**Issue by xx-7** [smol-rs/fastrand#21]
fastrand::seed(7);
println!("seed 7 after: {}", fastrand::u32(..));

let rng = fastrand::Rng::new();
let bytes: Vec<u8> = repeat_with(|| rng.u8(..)).take(100).collect();
println!("rng random bytes {:?}", bytes);

bytes same.

**Comment by taiki-e** [comment]
[`fastrand::seed`](https://docs.rs/fastrand/latest/fastrand/fn.seed.html) updates [the thread-local `RNG`](https://github.com/smol-rs/fastrand/blob/1d64e8aad20f30d4cc0bfc5466ee3c0c1eeac5ae/src/lib.rs#L524), and [`Rng::new`](https://docs.rs/fastrand/latest/fastrand/struct.Rng.html#method.new) refers to [the updated `RNG`](https://github.com/smol-rs/fastrand/blob/1d64e8aad20f30d4cc0bfc5466ee3c0c1eeac5ae/src/lib.rs#L277).

If you want to create an instance of `Rng` with seed without updating the thread-local `RNG`, you can use [`Rng::with_seed`](https://docs.rs/fastrand/latest/fastrand/struct.Rng.html#method.with_seed).
