### ISSUE TITLE
Add a way to seed the thread local default generator

### ISSUE THREAD

**Issue by notgull** [smol-rs/fastrand#28]
It would be nice to have a way to seed the `RNG` generator used for the module-level methods and for seeding the `Rng` structs by default. Maybe a `seed()` function or a `FASTRAND_TLS_SEED` environment variable.

**Comment by taiki-e** [comment]
> a `seed()` function

See https://docs.rs/fastrand/latest/fastrand/fn.seed.html

**Comment by notgull** [comment]
Not sure how I missed that, thank you!
