### ISSUE TITLE
clone() does not behave as expected

### ISSUE THREAD

**Issue by ra1u** [smol-rs/fastrand#36]
This fails, but I think it should not.

~~~rust
let mut rng_tx = fastrand::Rng::new();
let mut rng_rx = rng_tx.clone();
assert!(rng_tx.get_seed() == rng_rx.get_seed());
~~~

**Comment by taiki-e** [comment]
How does `rand` handle this case? It would be preferable to provide the same behavior as they do.

**Comment by ra1u** [comment]
It is auto derived. So it basically works by cloning internal state. 
https://docs.rs/rand/latest/src/rand/rngs/small.rs.html#80

**Comment by taiki-e** [comment]
Hmm, looking at the PR that added Clone impl (https://github.com/smol-rs/fastrand/pull/4 by @cloudhead), it seems that the current behavior is intentional?

**Comment by cloudhead** [comment]
It was intentional yes, as pointed out by the docs. Perhaps the `clone` function should be renamed to `fork`, and `clone` should be a regular clone.

**Comment by ra1u** [comment]
I am not sure that was intentional. For example current pull request https://github.com/smol-rs/fastrand/pull/38/commits/3e11c107240ae06f58716287462cae84804202c3 still passes same doctest as it was defined in https://github.com/smol-rs/fastrand/blob/master/src/lib.rs#L101-L113   and covers clone() related properties.

**Comment by cloudhead** [comment]
See the first line of the PR: `Useful for "splitting" the RNG when passing it down to sub-components/functions.`

By "splitting" it's meant that we generate a new RNG that isn't equal to the previous one. The documentation also explains that we *derive* a generator from the previous one. The test is also carefully chosen not to compare the derived generator with the original generator.

The problem is really the name chosen: "clone", so I'd propose we implement actual cloning under the clone function, and move the current clone functionality to a new function called "fork".

**Comment by ra1u** [comment]
I see.
Related to split: I think that split Rng should not be correlated with sourced Rng and implementation of split() should address that.

**Comment by ra1u** [comment]
Let me bump this with suggested improvement to `fork()`

Once rng is forked it is expected that output of each generator is uncorrelated with each other. For example if one splits generator for use in multiple threads, each generator should generate different numbers. 

I suggest we have public function that makes forking clear.

    pub fn fork(self) -> (Self,Self)
 
And implementation, for example

~~~~ rust
pub fn fork(self) -> (Self, Self) {
    let rand_a: u64 = 0xc0d43516ee92d71f;
    let rand_b: u64 = 0x91b6dcec5810da71;
    (
        Self::with_seed(self.gen_u64() ^ rand_a),
        Self::with_seed(self.gen_u64() ^ rand_b),
    )
}
~~~~

**Comment by cloudhead** [comment]
That is creating two forks though. It's a bit impractical as an API because you move self, and you return a tuple, so you can't just do eg.:
```rust
let base = Rng::new();
thread1(base.fork());
thread2(base.fork());
thread3(base.fork());
```

**Comment by ra1u** [comment]
I see your point @cloudhead .  It less ergonomic compared to moving tuple around.

I guess we have two options. What is your opinion of

~~~ rust
fn fork(&self) -> Self
~~~
vs
~~~ rust
fn fork(&mut self) -> Self
~~~

**Comment by cloudhead** [comment]
Hmm, so I would opt for `fork(&self)` simply because the other functions like `i32(..)`, `u8(..)` etc. all take a `&self`, and this function is similar in a way: it is producing a random value, but that value happens to be another Rng.

**Comment by notgull** [comment]
My personal vote is for `fork(&self)`.

**Comment by Bluefinger** [comment]
I went with `fork` for my `turborand` library after initially copying `fastrand` API regarding cloning, so to me it makes sense.

**Comment by ra1u** [comment]
There is PR available and should include features and interface as discussed here. https://github.com/smol-rs/fastrand/pull/38 
Let me know if I missed something and how we can push this forward.

**Comment by zseri** [comment]
`fork(&mut self)` would now make more sense, given we removed interior mutability.

**Comment by ra1u** [comment]
Related to PR https://github.com/smol-rs/fastrand/pull/49. Is it bug or feature that forked rng is correlated with sourced rng?

**Comment by notgull** [comment]
> Is it bug or feature that forked rng is correlated with sourced rng?

Could you please clarify?

**Comment by ra1u** [comment]
When forking rng I would expect that generating numbers from each rng is uncorrelated form other rng (they each generate different numbers).

Given this code from PR https://github.com/smol-rs/fastrand/blob/a19aeabfff505cb157c584d8034bffabfaaa8b8f/src/lib.rs#L293-L295
It seems to me that generators will start generating same numbers, as seed from one generator is  just retarded by one seed step.

I guess this holds (need to check and compile)

~~~ rust
let mut ra = Rng::new();
let mut rb = ra.fork();
let _ = rb.i64();

assert_eq!(ra.i64(),rb.i64());
~~~

For this reason following workaround was used in my PR
https://github.com/ra1u/fastrand/blob/d272328b1ff1a4374c7f7c3cd06ff4510a473d1e/src/lib.rs#L170-L176
