### ISSUE TITLE
Use of `instant` crate imcompatible w/ MIT license?

### ISSUE THREAD

**Issue by zeenix** [smol-rs/fastrand#54]
I ran `cargo lichking check` against zbus and according to that [BSD-3-Clause license](https://choosealicense.com/licenses/bsd-3-clause/) of `instant` is incompatible with MIT license of zbus. Seems this is the only crate that brings in this dep. IANAL so can't be sure this is a problem but I wanted to bring this to attention.

@smol-rs/admins ?

**Comment by notgull** [comment]
IANAL, but if I remember right the main restriction of the BSD 3 clause license over the MIT/Apache2 license is that you can't use the package for advertising. Realistically I don't think this is an issue, since there are plenty of MIT-licensed packages that use `instant` (`winit` comes to mind).

**Comment by notgull** [comment]
> Seems this is the only crate that brings in this dep.

`async-lock` also uses the `instant` crate, as a heads up.

**Comment by zeenix** [comment]
> IANAL, but if I remember right the main restriction of the BSD 3 clause license over the MIT/Apache2 license is that you can't use the package for advertising.

Right and in general when you statically link two libs under different licenses, doesn't the more restrictive license becomes the effective one?

> Realistically I don't think this is an issue, since there are plenty of MIT-licensed packages that use `instant` (`winit` comes to mind).

True. That does make it unlikely that there is a problem but I don't think "others are doing it too" argument would hold in a court. :)
