### ISSUE TITLE
How to generate random number 58 bit length ?

### ISSUE THREAD

**Issue by Manosuper** [smol-rs/fastrand#67]
Subj.

Thank you for your answer.

Thank you for your REALLY FAST GENERATOR !

**Comment by notgull** [comment]
If I'm remembering my bit math correctly...

```rust
fastrand::u64(..) & ((1 << 59) - 1)
```

What is the application? I'm curious.

**Comment by notgull** [comment]
The `fastrand` Python package is unrelated to this crate
