### ISSUE TITLE
"the paper"

### ISSUE THREAD

**Issue by lolbinarycat** [smol-rs/fastrand#75]
`src/specialized/pclmulqdq.rs` references "the paper" several times, and as far as i can tell, none of the files in this repo mentions any paper whatsoever.

**Comment by taiki-e** [comment]
> src/specialized/pclmulqdq.rs

It looks like you have opened an issue in the wrong repository.
There is no such file in this repository: https://github.com/smol-rs/fastrand/tree/master/src
