### ISSUE TITLE
fails to build with musl rust

### ISSUE THREAD

**Issue by lolbinarycat** [smol-rs/fastrand#80]
i tried using nixpkgs `pkgsMusl.rustc` to build a package that depends on this crate, but it fails due to a glibc-specific function in `std::sys` being called.

**Comment by notgull** [comment]
`master` tests pass on my Alpine Linux machine.

![image](https://github.com/smol-rs/fastrand/assets/19805233/0646d857-1ee9-4b33-b5b7-d1be1f730267)

Could you provide more information?

**Comment by lolbinarycat** [comment]
> Could you provide more information?

once i'm back at my laptop, sure.

could you provide the output of `ldd /usr/bin/ldd`?

**Comment by taiki-e** [comment]
Maybe related: https://github.com/rust-lang/rust/issues/121980

**Comment by taiki-e** [comment]
> it fails due to a glibc-specific function in **`std::sys`** being called.

Given the error is occurring here, it is very likely that the problem is nothing related to fastrand.
Perhaps the rust-lang/rust issue I linked to above is the cause, but if you are still seeing the problem, please report the issue at where the thing that actually caused the error is defined.
