### ISSUE TITLE
FastRand's dependency `instant` is unmaintained

### ISSUE THREAD

**Issue by MrCartaaa** [smol-rs/fastrand#94]
Running `cargo check deny advisories` Fails.

According to the output, `instant` is unmaintained.

**Comment by MrCartaaa** [comment]
Here is the output.

![Screenshot 2024-11-24 114244](https://github.com/user-attachments/assets/3455ab77-99fc-4f91-bd97-690a2969bdd6)

**Comment by taiki-e** [comment]
fastrand 1.9.0 (latest: 2.2.0), futures-lite 1.13.0 (latest: 2.5.0), and async-io 1.13.0 (latest: 2.4.0) are all old versions.
Consider using the latest versions.
